### ISSUE TITLE
Tracking: cite extraction / linking nitpicks

### ISSUE THREAD

**Issue by jcushman** [harvard-lil/capstone#1427]
- [ ] cite urls should have normalized reporter names to avoid a redirect on click
- [ ] "123 U. S. 456" urls redirect to /u-s/123/456/, which isn't found
- [ ] "2 or 3" is extracted as "2 Or. 3"
- [ ] Footnote numbers are included in cite extraction, like "[footnote 1]: A 403(b) ..." is matched as "[1 A 403](https://cite.capapi.org/wis-2d/362/524/)"
- [ ] Citations shouldn't match if they start with 0, like "[09 B 17236, 09 A 788](https://cite.capapi.org/br/535/803/)"

**Comment by jcushman** [comment]
Closing this in favor of https://github.com/harvard-lil/capstone/projects/45
