### ISSUE TITLE
End to End Playwright tests

### ISSUE THREAD

**Issue by sabzo** [harvard-lil/capstone#2087]
The goal is to create a series of tests that will launch browsers, a test server, and test if certain actions on UI elements return expected results.

## Tasks
* **homepage** 
   * [x] test if map functionality points to the correct page and updates information on the left side
   * [x] test if clicking on svg map goes to the right place (this works with the exception of small states or states not in the mainland)
* **search**:
  * [ ] pagination
  * [ ] counts
  * [ ] download buttons if it works, 
  * [ ] update search
  * [ ] search tag is shown at the top, 
  * [ ] show api call
  * [ ] link to trends page,
* **Trends**
  * [ ] frequency of search term, 
  * [ ] wildcard testing
  * [ ] make sure that when click is made something renders back
* **Case**:
  * [ ] left navigation bar (is js and needs to be tested)
* **Case editor**:
  * [ ]  edit case based on ocr 
    * [ ] testing if edit case updates, 
    * [ ] does the page load, 
    * [ ] render, 
    * [ ] can you save a word clicked,
    * [ ] if a change is made does it break build on other pages?
* **Timeline** 
  * [ ] does clicking create timeline load timeline? 
  * [ ] Can user edit cases, add a case, basically crud operations... (looking at the code as well)
  
  Reference: PyTest, PyTest fixtures, Django liveservr, and Perma testing
  Ensure build still works
