### ISSUE TITLE
[TRACKING] Python Packages

### ISSUE THREAD

**Issue by arichiv** [harvard-lil/capstone#745]
- [x] Update packages without new incompatibilities
- [ ] Update pytest to 4.x
- [ ] Update pyquery to 1.4.x
- [ ] Update django-storages to 1.7.x
- [ ] Update flake8 to 3.6.x
- [ ] Update boto3 (and moto) to 1.9.x 
- [ ] Update django to 2.1.x
- [ ] Update django-model-utils on next release after https://github.com/jazzband/django-model-utils/issues/331 is resolved
- [ ] Update email-normalize on next release after https://github.com/gmr/email-normalize/pull/3 is resolved
- [ ] Update djangorestframework-filters on next release
- [x] Update pip-tools on next release
